# - workflow - n4
#   - jobs - inspecao (bloco 1)
#     - steps - instalar dependencies
#     - steps - executar script de lint
#   - jobs - unidade (bloco 1)
#     - needs: inspecao
#     - steps - instalar dependencies
#     - steps - executar script de testes de unidade
#   - jobs - e2e-tests (bloco 2)
#     - needs: unidade
#     - steps - instalar dependencies
#     - steps - instalar subir app localmente
#     - steps - instalar browsers
#     - steps - run e2e scripts
#     - steps - publish reports
#   - jobs - deploy (bloco 3)
#     - needs: e2e-tests
#     - steps - instalar depedendencies
#     - steps - gerar artefatos de aplicacao
#     - steps - publish app in env

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installing dependencies
        run: yarn

      - name: Validating linting
        run: yarn lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v4

      - name: Installing dependencies
        run: yarn

      - name: Running unit tests
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      # clone do projeto. Comando pra usar uma action
      - uses: actions/checkout@v4

      # instalacao do node
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: latest

      # instalacao das dependencies
      - name: Installing dependencies
        # ou yarn install
        run: yarn

      # instalacao do Playwright
      - name: Installing Playwright
        run: yarn playwright install

      # executando testes e2e
      - name: Running e2e tests
        run: yarn run e2e

      - name: Publishing results in PR
        uses: dorny/test-reporter@v1
        if: ${{ !cancelled() }}
        with:
          name: e2e-report
          path: './test-results/results.xml'
          reporter: java-junit

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    steps:
      - name: Simulating deploy
        run: echo "simulating deploy message"
